apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: api
  namespace: helpdesk
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mailer
  namespace: helpdesk
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: frontend
  namespace: helpdesk
spec:
  lookupPolicy:
    local: true
