apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: chrif0709-dev
type: Opaque
stringData:
  POSTGRES_USER: helpdesk
  POSTGRES_PASSWORD: helpdesk123
  POSTGRES_DB: helpdesk
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: chrif0709-dev
type: Opaque
stringData:
  JWT_SECRET: wYQlo0LvDo67tzXA+1g06RdMJNCCMuAhXaVLOL2RxxU=
  DATABASE_URL: postgresql://helpdesk:helpdesk123@postgres:5432/helpdesk
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "465"
  SMTP_USER: mohamed.cherif.khcherif@gmail.com
  SMTP_PASS: iudr ppzq adqi cirs
  SMTP_FROM: noreply@helpdesk.local
